### ISSUE TITLE
Index out of range exception for paired end reads

### ISSUE THREAD

**Issue by dawnmy** [ITBE-Lab/MA#8] opened 2021-01-31 20:06 UTC
I was trying to run MA on paired end short reads with:

```
$ maCMD -x dbs/ma.json -p Illumina_Paired -i datasets/short_read.qc_1.fq -m datasets/short_read.qc_2.fq -o outputs/metax.pe.sam
```

But I got the error below:
```shell
starting alignment.
Drop exception (different thread threw already): Index out of range
Drop exception (different thread threw already): Index out of range
Drop exception (different thread threw already): Index out of range
Throw exception
Error:
Index out of range
```
It was fine with single end file or comma separated list of files.

**Comment by MarkusRainerSchmidt** [comment] 2021-02-01 06:06
Your command looks like it should work just fine.

Can you give me the two read-files you are using and tell me the commit you are working with?
Without that, I won't be able to figure out what causes the error.
My email is: schmidtm@hanyang.ac.kr

**Comment by dawnmy** [comment] 2021-02-01 17:33
I used the version from bioconda:
```
ma   1.1.1  py37h8270d21_1  bioconda
```
I have send you the minimal example PE reads files per email.

**Comment by MarkusRainerSchmidt** [comment] 2021-02-04 06:51
To summarize our e-mail correspondence:

I couldn't reproduce the error on my end, but version 1.1.2 (https://github.com/ITBE-Lab/MA/commit/96ebb636f3828b83a35fb52c76aeb7852c37198b) seems to resolve the problem. 

Therefore, I'll close this issue for now.

**Closed as completed by MarkusRainerSchmidt** 2021-02-04 06:51 UTC
Labels: bug
